*******************************************************************************************
Message:EVERYTHING IS AWFUL!!!!!!
*******************************************************************************************
*******************************************************************************************
Traceback (most recent call last):
  File "test_simple_logger.py", line 27, in test_warnings
    raise Exception("EVERYTHING IS exceptionally AWFUL!!!!!!")
Exception: EVERYTHING IS exceptionally AWFUL!!!!!!

*******************************************************************************************
*******************************************************************************************
Message:EVERYTHING IS AWFUL!!!!!!
Traceback (most recent call last):
  File "test_simple_logger.py", line 27, in test_warnings
    raise Exception("EVERYTHING IS exceptionally AWFUL!!!!!!")
Exception: EVERYTHING IS exceptionally AWFUL!!!!!!

*******************************************************************************************
